export const CONST = {
   ADD_POST: "POST/ADD_POST",
   FETCH_POST: "POST/FETCH_POST",
   SHOW_LOADING: "APP/SHOW_LOADING",
   HIDE_LOADING: "APP/HIDE_LOADING",
   SHOW_ERR: "APP/SHOW_ERR",
   HIDE_ERR: "APP/HIDE_ERR"
}
